version: '3.8'

name: beq

services:
  # Vector database for RAG
  qdrant:
    image: qdrant/qdrant:latest
    container_name: beq-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # BeQ Microservices
  orchestrator:
    build:
      context: .
      dockerfile: services/orchestrator/Dockerfile
    container_name: beq-orchestrator
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=${DATABASE_URL}
      - SCHEDULER_SERVICE_URL=http://scheduler:8001
      - RAG_SERVICE_URL=http://rag-recommender:8002
      - CALENDAR_SERVICE_URL=http://calendar-integration:8003
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./services/orchestrator:/app
    networks:
      - beq-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 5

  scheduler:
    build:
      context: .
      dockerfile: services/scheduler/Dockerfile
    container_name: beq-scheduler
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o}
    ports:
      - "8001:8001"
    restart: unless-stopped
    networks:
      - beq-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 5s
      retries: 5

  rag-recommender:
    build:
      context: .
      dockerfile: services/rag-recommender/Dockerfile
    container_name: beq-rag-recommender
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=${DATABASE_URL}
      - QDRANT_URL=http://qdrant:6333
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o}
    ports:
      - "8002:8002"
    depends_on:
      qdrant:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - beq-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 5s
      retries: 5

  calendar-integration:
    build:
      context: .
      dockerfile: services/calendar-integration/Dockerfile
    container_name: beq-calendar-integration
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
      - SUPABASE_URL=https://ncuqhnggwiayzqvrelql.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jdXFobmdnd2lheXpxdnJlbHFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyODkwODcsImV4cCI6MjA3Mzg2NTA4N30.EQG8bwa0uhYv3u8TkH5bHiTJoJupcG8m_ETDLUuos9I
      - SUPABASE_SERVICE_ROLE_KEY=${NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY}
    ports:
      - "8003:8003"
    restart: unless-stopped
    volumes:
      - ./services/calendar-integration/.env:/app/.env
    networks:
      - beq-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 5s
      retries: 5

  # Frontend application
  web:
    build:
      context: ./clients/web
      dockerfile: Dockerfile
    container_name: beq-web
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_ORCHESTRATOR_API_URL=http://localhost:8000
      - NEXT_PUBLIC_SCHEDULER_API_URL=http://localhost:8001
      - NEXT_PUBLIC_RAG_API_URL=http://localhost:8002
      - NEXT_PUBLIC_CALENDAR_API_URL=http://localhost:8003
      - NEXT_PUBLIC_ENVIRONMENT=development
      - NEXT_PUBLIC_SUPABASE_URL=https://ncuqhnggwiayzqvrelql.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jdXFobmdnd2lheXpxdnJlbHFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyODkwODcsImV4cCI6MjA3Mzg2NTA4N30.EQG8bwa0uhYv3u8TkH5bHiTJoJupcG8m_ETDLUuos9I
      - NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jdXFobmdnd2lheXpxdnJlbHFsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1ODI4OTA4NywiZXhwIjoyMDczODY1MDg3fQ.FvxvPeqgGVkkZ8Tn24SRWRy5HxLpXXqIbST-YtOl7OI
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3000:3000"
    depends_on:
      - orchestrator
    restart: unless-stopped
    volumes:
      - ./clients/web:/app
      - /app/node_modules
    networks:
      - beq-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  qdrant_data:

networks:
  beq-network:
    driver: bridge
    name: beq-network
